#!/bin/bash

# toggles on and off between caffeinate

read -r state<~/Programs/bin/caffine.state

if [ "$state" = "true" ]; then
  caffeinate -disu &
else
  killall caffeinate
fi

~/Programs/bin/toggle c t
~/Programs/bin/toggle_bool $state > ~/Programs/bin/caffine.state
