# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@prettier/plugin-xml-3.2.2" = {
      name = "_at_prettier_slash_plugin-xml";
      packageName = "@prettier/plugin-xml";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@prettier/plugin-xml/-/plugin-xml-3.2.2.tgz";
        sha512 = "SoE70SQF1AKIvK7LVK80JcdAe6wrDcbodFFjcoqb1FkOqV0G0oSlgAFDwoRXPqkUE5p/YF2nGsnUbnfm6471sw==";
      };
    };
    "@xml-tools/parser-1.0.11" = {
      name = "_at_xml-tools_slash_parser";
      packageName = "@xml-tools/parser";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@xml-tools/parser/-/parser-1.0.11.tgz";
        sha512 = "aKqQ077XnR+oQtHJlrAflaZaL7qZsulWc/i/ZEooar5JiWj1eLt0+Wg28cpa+XLney107wXqneC+oG1IZvxkTA==";
      };
    };
    "chevrotain-7.1.1" = {
      name = "chevrotain";
      packageName = "chevrotain";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chevrotain/-/chevrotain-7.1.1.tgz";
        sha512 = "wy3mC1x4ye+O+QkEinVJkPf5u2vsrDIYW9G7ZuwFl6v/Yu0LwUuT2POsb+NUWApebyxfkQq6+yDfRExbnI5rcw==";
      };
    };
    "prettier-3.1.0" = {
      name = "prettier";
      packageName = "prettier";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-3.1.0.tgz";
        sha512 = "TQLvXjq5IAibjh8EpBIkNKxO749UEWABoiIZehEPiY4GNpVdhaFKqSTu+QrlU6D2dPAfubRmtJTi4K4YkQ5eXw==";
      };
    };
    "regexp-to-ast-0.5.0" = {
      name = "regexp-to-ast";
      packageName = "regexp-to-ast";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/regexp-to-ast/-/regexp-to-ast-0.5.0.tgz";
        sha512 = "tlbJqcMHnPKI9zSrystikWKwHkBqu2a/Sgw01h3zFjvYrMxEDYHzzoMZnUrbIfpTFEsoRnnviOXNCzFiSc54Qw==";
      };
    };
  };
  args = {
    name = "dotfiles";
    packageName = "dotfiles";
    src = ./.;
    dependencies = [
      sources."@prettier/plugin-xml-3.2.2"
      sources."@xml-tools/parser-1.0.11"
      sources."chevrotain-7.1.1"
      sources."prettier-3.1.0"
      sources."regexp-to-ast-0.5.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
