#!/bin/bash

# yabai -m query --spaces --space | jq '.windows | .[]' | xargs -n1 -I{} yabai -m window {}  --toggle border

# transition -> 1 window
if [ $(yabai -m query --spaces --space | jq '.windows' | jq length) -eq 1 ]; then
  # turn off borders
  yabai -m query --spaces --space | jq '.windows | .[]' | xargs -n1 ~/Programs/bin/border_off
  # turn off gaps and padding
  yabai -m space --padding abs:0:0:0:0; yabai -m space --gap abs:0
  # yabai -m space --toggle padding; yabai -m space --toggle gap
# 1 window -> 2 windows
elif [ $(yabai -m query --spaces --space | jq '.windows' | jq length) -eq 2 ] && [ "$1" == "inc" ]; then
  # turn on border for each window
  yabai -m query --spaces --space | jq '.windows | .[]' | xargs -n1 ~/Programs/bin/border_on
  # turn on gaps and padding
  yabai -m space --padding abs:20:20:20:20; yabai -m space --gap abs:10
fi
