#!/bin/bash

# toggles the yabai menu bar

# run as get_icon state icon_if_off icon_if_on
# reversed becauase state read in is actually the *next* state
function get_icon
{
  if [ "$1" = "true" ]; then
    echo $2
  else
    echo $3
  fi
}

lspaces="                                                                                                                                                                                                                                                                                                     "
lespace="            "
sspaces="                                                                                                                                                                                                                                            "
sespace="           "

# change spacing based off monitor resolution
# laptop width
if [ $(~/Programs/bin/res) -eq 2880 ]; then
  spaces=$sspaces
  espace=$sespace
else
  spaces=$lspaces
  espace=$lespace
fi

# read in the states from right to left
read -r state1<~/Programs/bin/caffine.state
read -r state2<~/Programs/bin/flux.state
read -r state3<~/Programs/bin/zap.state
read -r state4<~/Programs/bin/anime.state

yabai -m config status_bar_space_icon_strip       6 7 8 9 \
"${spaces}$(get_icon $state4  )${espace}$(get_icon $state3  )${espace}$(get_icon $state2  )${espace}$(get_icon $state1  )"
