#!/bin/bash

# toggles the yabai menu bar
# called via toggle t c ... c c t
# where t is to toggle the icon and c is to let it remain the same

function update_state
{
  if [ "$1" = "t" ]; then
    result="$(~/Programs/bin/toggle_bool $2)"
  else
    result=$2
  fi

  echo $result
}

# run as get_icon state icon_if_off icon_if_on
# reversed becauase state read in is actually the *next* state
function get_icon
{
  if [ "$1" = "true" ]; then
    echo $2
  else
    echo $3
  fi
}

lspaces="                                                                                                                                                                                                                                                                                                                                   "
lespace="            "
sspaces="                                                                                                                                                                                                                                                                                      "
sespace="            "

# change spacing based off monitor resolution
# laptop width
if [ $(~/Programs/bin/res) -eq 2880 ]; then
  spaces=$sspaces
  espace=$sespace
else
  spaces=$lspaces
  espace=$lespace
fi

read -r state1<~/Programs/bin/zap.state
read -r state2<~/Programs/bin/caffine.state

state1="$(update_state $1 $state1)"
state2="$(update_state $2 $state2)"

yabai -m config status_bar_space_icon_strip       6 7 8 9 "${spaces}$(get_icon $state1  )${espace}$(get_icon $state2  )"
