#!/usr/bin/env fish
# ran after yadm clone repo
# run with  yadm bootstrap

### vim

# vim-plug: https://github.com/junegunn/vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

